#!/bin/bash

MUTED=$(pacmd list-sources | awk '/muted/ { print $2 }' | tail -1)

if [[ $MUTED == "yes" ]]; then
  pactl set-source-mute alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.analog-mono 0
else
  pactl set-source-mute alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.analog-mono 1
fi