#!/bin/bash

MUTED=$(pacmd list-sources | awk '/muted/ { print $2 }')
echo $MUTED

if [[ $MUTED == *"yes"* ]]; then
  pactl set-source-mute alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-chat 0
else
  pactl set-source-mute alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-chat 1
fi