#!/bin/bash

FILE=$HOME/.spotify

touch $FILE
while true; do
  NOW_PLAYING=$(playerctl metadata --format "{{ artist }} - {{ title }}")
  echo $NOW_PLAYING > $FILE
  echo "Now playing: $NOW_PLAYING"
  sleep 1
done
rm $FILE
